// <auto-generated />
using System;
using ApiOne.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiOne.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220205154824_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiOne.Data.Application", b =>
                {
                    b.Property<int>("ApplicationNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationNum"), 1L, 1);

                    b.Property<string>("AddressBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BranchBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchBankAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditManagerId")
                        .HasColumnType("int");

                    b.Property<int>("CreditType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PassportNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequestedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ScoringStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Snils")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationNum");

                    b.ToTable("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
